# Standalone config - don't inherit from parent directories
inherit_from: []

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 250
